### ISSUE TITLE
Issues running the package

### ISSUE THREAD

**Issue by EugeneHlushko** [digimuza/iterparse#8]
Error I see after importing the package as `import { csvRead } from 'iterparse'`, installed using `npm`
```
node_modules/ix/Ix.d.ts:6:10 - error TS2440: Import declaration conflicts with local declaration of 'GroupedAsyncIterable'.

6 import { GroupedAsyncIterable } from './asynciterable/groupby';
```

```
node -v
v15.4.0

npm -v
7.0.15
```

`ix` is only required by `iterparse` in my dependencies according to the `package-lock.json`

**Comment by digimuza** [comment]
I will check this issue. Can you provide more details regarding this issue.
I can't recreate :(

**Comment by digimuza** [comment]
What typescript version do you use?

Do you have "skipLibCheck": true, in your tsconfig file? If no this is recommended setting for typescript
